version: '3.8'

services:
  backend-express:
    build:
      context: .
    ports:
      - "4020:3000"
    restart: unless-stopped
    depends_on:
      - databaseService

  
  databaseService:
    image: mongo:5
    ports:
      - "27018:27017"
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata: